import type { BoardDefinition } from "../../types/monday.js";

export const planAdquisicionesBoard: BoardDefinition = {
  key: "plan_adquisiciones",
  name: "Plan de Adquisiciones",
  description: "Ciclo completo de cada proceso según metodologías del organismo financiador.",
  level: "tactico",
  pmiDomains: ["Planificación", "Trabajo"],
  groups: [
    { id: "bienes", title: "Bienes", color: "#579bfc" },
    { id: "obras", title: "Obras", color: "#ff642e" },
    { id: "servicios_no_consultoria", title: "Servicios No Consultoría", color: "#fdab3d" },
    { id: "consultoria_firmas", title: "Consultoría Firmas", color: "#a25ddc" },
    { id: "consultoria_individual", title: "Consultoría Individual", color: "#00c875" },
  ],
  columns: [
    { id: "codigo_proceso", title: "Código Proceso", type: "text", description: "ID: LPI-001, SBCC-003, CD-002" },
    { id: "descripcion", title: "Descripción", type: "text", description: "Objeto de la adquisición" },
    { id: "metodo", title: "Método", type: "dropdown", description: "LPI, LPN, SBCC, SBC, SBQ, SBMC, CD, Comparación Precios, Directa" },
    { id: "tipo_revision", title: "Tipo Revisión", type: "status", description: "Previa (No Objeción) / Posterior" },
    { id: "monto_estimado", title: "Monto Estimado (USD)", type: "numbers" },
    { id: "monto_adjudicado", title: "Monto Adjudicado (USD)", type: "numbers" },
    { id: "fuente", title: "Fuente", type: "dropdown", description: "Préstamo, Contrapartida, Donación" },
    { id: "categoria_gasto", title: "Categoría de Gasto", type: "dropdown", description: "Según convenio de préstamo" },
    { id: "etapa_actual", title: "Etapa Actual", type: "status", description: "Pipeline completo de adquisición" },
    { id: "fecha_inicio", title: "Fecha Inicio", type: "date" },
    { id: "fecha_publicacion", title: "Fecha Publicación", type: "date" },
    { id: "fecha_adjudicacion_est", title: "Fecha Adjudicación Est.", type: "date" },
    { id: "fecha_firma", title: "Fecha Firma", type: "date" },
    { id: "dias_en_etapa", title: "Días en Etapa", type: "numbers", description: "Días desde último cambio de etapa" },
    { id: "alerta_retraso", title: "Alerta Retraso", type: "status", description: "Auto: Verde / Amarillo / Rojo" },
    { id: "actividad_poa", title: "Actividad POA", type: "connect_boards", description: "Vinculación con POA" },
    { id: "contrato_generado", title: "Contrato Generado", type: "connect_boards", description: "Link a Contratos" },
    { id: "documentos", title: "Documentos", type: "file", description: "TdR, informes evaluación, No Objeciones" },
    { id: "responsable", title: "Responsable", type: "people" },
    { id: "notas", title: "Notas", type: "long_text" },
  ],
  statusLabels: {
    etapa_actual: [
      { index: 0, label: "Planificado", color: "#c4c4c4" },
      { index: 1, label: "TdR", color: "#579bfc" },
      { index: 2, label: "No Obj. TdR", color: "#a25ddc" },
      { index: 3, label: "Publicación", color: "#0086c0" },
      { index: 4, label: "Ofertas", color: "#fdab3d" },
      { index: 5, label: "Evaluación", color: "#ff642e" },
      { index: 6, label: "No Obj. Informe", color: "#a25ddc" },
      { index: 7, label: "Adjudicación", color: "#037f4c" },
      { index: 8, label: "Firma", color: "#00c875" },
      { index: 9, label: "Ejecución", color: "#00c875" },
      { index: 10, label: "Cerrado", color: "#333333" },
    ],
    tipo_revision: [
      { index: 0, label: "Previa (No Objeción)", color: "#a25ddc" },
      { index: 1, label: "Posterior", color: "#579bfc" },
    ],
    alerta_retraso: [
      { index: 0, label: "Verde", color: "#00c875" },
      { index: 1, label: "Amarillo", color: "#fdab3d" },
      { index: 2, label: "Rojo", color: "#e2445c" },
    ],
  },
};
